version: '3.9'

name: feathr

networks:
  feathr:

volumes:
  pgsql-rbac:
  pgsql-registry:


services:

  rbac:
    build:
      context: ../../registry/
      dockerfile: access_control/Dockerfile
    ports:
      - "18000:${RBAC_LISTENING_PORT}"
    environment:
      RBAC_DATABASE: ${RBAC_DATABASE}
      RBAC_CONNECTION_STR: ${RBAC_CONNECTION_STR}
      RBAC_LISTENING_PORT: ${RBAC_LISTENING_PORT}
      RBAC_API_BASE: ${RBAC_API_BASE}
      RBAC_API_CLIENT_ID: ${RBAC_API_CLIENT_ID}
      RBAC_API_AUDIENCE: ${RBAC_API_AUDIENCE}
      RBAC_AAD_TENANT_ID: ${RBAC_AAD_TENANT_ID}
      RBAC_AAD_INSTANCE: ${RBAC_AAD_INSTANCE}
      RBAC_DEFAULT_ADMIN: ${RBAC_DEFAULT_ADMIN}
      FEATHR_REGISTRY_URL: "http://registry:${FEATHR_REGISTRY_LISTENING_PORT}${FEATHR_API_BASE}"
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
    networks:
      - feathr
    depends_on:
      - pgsql-rbac
    restart: always

  registry:
    build:
      context: ../../registry/
      dockerfile: sql-registry/Dockerfile
    ports:
      - "8001:${FEATHR_REGISTRY_LISTENING_PORT}"
    environment:
      FEATHR_REGISTRY_DATABASE: ${FEATHR_REGISTRY_DATABASE}
      FEATHR_REGISTRY_CONNECTION_STR: ${FEATHR_REGISTRY_CONNECTION_STR}
      FEATHR_REGISTRY_LISTENING_PORT: ${FEATHR_REGISTRY_LISTENING_PORT}
      FEATHR_API_BASE: ${FEATHR_API_BASE}
      REGISTRY_DEBUGGING: ${REGISTRY_DEBUGGING:-0}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
    networks:
      - feathr
    depends_on:
      - pgsql-registry
    restart: always

  pgsql-rbac:
    image: postgres:15.4
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - '${RBAC_PGSQL_PORT}:5432'
    environment:
      POSTGRES_DB: ${RBAC_PGSQL_DB}
      POSTGRES_USER: ${RBAC_PGSQL_USER}
      POSTGRES_PASSWORD: ${RBAC_PGSQL_PASSWORD}
    volumes:
      - 'pgsql-rbac:/var/lib/postgresql/data'
    networks:
      - feathr
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${RBAC_PGSQL_DB}'
        - '-U'
        - '${RBAC_PGSQL_USER}'
      retries: 5
      timeout: 5s
    restart: always

  pgsql-registry:
    image: postgres:15.4
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - '${FEATHR_PGSQL_PORT}:5432'
    environment:
      POSTGRES_DB: ${FEATHR_PGSQL_DB}
      POSTGRES_USER: ${FEATHR_PGSQL_USER}
      POSTGRES_PASSWORD: ${FEATHR_PGSQL_PASSWORD}
    volumes:
      - 'pgsql-registry:/var/lib/postgresql/data'
    networks:
      - feathr
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${FEATHR_PGSQL_DB}'
        - '-U'
        - '${FEATHR_PGSQL_USER}'
      retries: 5
      timeout: 5s
    restart: always

  ui:
    build:
      context: ../../
      dockerfile: ui/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - feathr
    restart: always




