version: '3.9'

name: feathr

networks:
  feathr:

volumes:
  sqlite-data:

services:

  rbac:
    build:
      context: ../../registry/
      dockerfile: access_control/Dockerfile
    ports:
      - "18000:${RBAC_LISTENING_PORT}"
    environment:
      RBAC_DATABASE: ${RBAC_DATABASE}
      RBAC_CONNECTION_STR: ${RBAC_CONNECTION_STR}
      RBAC_LISTENING_PORT: ${RBAC_LISTENING_PORT}
      RBAC_API_BASE: ${RBAC_API_BASE}
      RBAC_API_CLIENT_ID: ${RBAC_API_CLIENT_ID}
      RBAC_API_AUDIENCE: ${RBAC_API_AUDIENCE}
      RBAC_AAD_TENANT_ID: ${RBAC_AAD_TENANT_ID}
      RBAC_AAD_INSTANCE: ${RBAC_AAD_INSTANCE}
      RBAC_DEFAULT_ADMIN: ${RBAC_DEFAULT_ADMIN}
      FEATHR_REGISTRY_URL: "http://registry:${FEATHR_REGISTRY_LISTENING_PORT}${FEATHR_API_BASE}"
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
    volumes:
      - sqlite-data:/tmp
    restart: always
    networks:
      - feathr

  registry:
    build:
      context: ../../registry/
      dockerfile: sql-registry/Dockerfile
    ports:
      - "8001:${FEATHR_REGISTRY_LISTENING_PORT}"
    environment:
      FEATHR_REGISTRY_DATABASE: ${FEATHR_REGISTRY_DATABASE}
      FEATHR_REGISTRY_CONNECTION_STR: ${FEATHR_REGISTRY_CONNECTION_STR}
      FEATHR_REGISTRY_LISTENING_PORT: ${FEATHR_REGISTRY_LISTENING_PORT}
      FEATHR_API_BASE: ${FEATHR_API_BASE}
      REGISTRY_DEBUGGING: ${REGISTRY_DEBUGGING:-0}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
    volumes:
      - sqlite-data:/tmp
    restart: always
    networks:
      - feathr

  ui:
    build:
      context: ../../
      dockerfile: ui/Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - feathr

