version: '3.9'

name: feathr

networks:
  feathr:

volumes:
  mssql-rbac:
  mssql-registry:


services:

  rbac:
    build:
      context: ../../registry/
      dockerfile: access_control/Dockerfile
    ports:
      - "18000:${RBAC_LISTENING_PORT}"
    environment:
      RBAC_DATABASE: ${RBAC_DATABASE}
      RBAC_CONNECTION_STR: ${RBAC_CONNECTION_STR}
      RBAC_LISTENING_PORT: ${RBAC_LISTENING_PORT}
      RBAC_API_BASE: ${RBAC_API_BASE}
      RBAC_API_CLIENT_ID: ${RBAC_API_CLIENT_ID}
      RBAC_API_AUDIENCE: ${RBAC_API_AUDIENCE}
      RBAC_AAD_TENANT_ID: ${RBAC_AAD_TENANT_ID}
      RBAC_AAD_INSTANCE: ${RBAC_AAD_INSTANCE}
      RBAC_DEFAULT_ADMIN: ${RBAC_DEFAULT_ADMIN}
      FEATHR_REGISTRY_URL: "http://registry:${FEATHR_REGISTRY_LISTENING_PORT}${FEATHR_API_BASE}"
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
    networks:
      - feathr
    depends_on:
      - mssql-rbac
    restart: always

  registry:
    build:
      context: ../../registry/
      dockerfile: sql-registry/Dockerfile
    ports:
      - "8001:${FEATHR_REGISTRY_LISTENING_PORT}"
    environment:
      FEATHR_REGISTRY_DATABASE: ${FEATHR_REGISTRY_DATABASE}
      FEATHR_REGISTRY_CONNECTION_STR: ${FEATHR_REGISTRY_CONNECTION_STR}
      FEATHR_REGISTRY_LISTENING_PORT: ${FEATHR_REGISTRY_LISTENING_PORT}
      FEATHR_API_BASE: ${FEATHR_API_BASE}
      REGISTRY_DEBUGGING: ${REGISTRY_DEBUGGING:-0}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
    networks:
      - feathr
    depends_on:
      - mssql-registry
    restart: always

  mssql-rbac:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '${RBAC_MSSQL_PORT}:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${RBAC_MSSQL_SA_PASSWORD}
    volumes:
      - mssql-rbac:/var/opt/mssql
    networks:
      - feathr
    restart: always

  mssql-registry:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '${FEATHR_MSSQL_PORT}:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${FEATHR_MSSQL_SA_PASSWORD}
    volumes:
      - mssql-registry:/var/opt/mssql
    networks:
      - feathr
    restart: always

  mssql-migration:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - mssql-rbac
      - mssql-registry
    volumes:
      - ../migrations/mssql:/sql-scripts
    command: >
        /bin/bash -c "sleep 15 && /opt/mssql-tools/bin/sqlcmd -S mssql-rbac -U SA -P ${RBAC_MSSQL_SA_PASSWORD} -d master -i /sql-scripts/init-rbac-db.sql
        && sleep 15 && /opt/mssql-tools/bin/sqlcmd -S mssql-registry -U SA -P ${FEATHR_MSSQL_SA_PASSWORD} -d master -i /sql-scripts/init-registry-db.sql
        && echo 'Databases were initialized'"
    networks:
      - feathr

  ui:
    build:
      context: ../../
      dockerfile: ui/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - feathr
    restart: always




